name: deploy demo to personal server

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    name: deploy demo to personal server
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Deploy website
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: web/personal/smartphoniker.tobiaspoertner.com/
          exclude: .git*/**
            - .git*
            - .github/*
            - **/*.scss
            - stylesheets/main.min.css.map
            - **/.*
            - **/*.sh
          dry-run: ${{ secrets.ENVIRONMENT }}
