name: Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync
        env:
          dest: "${{secrets.SSH_USERNAME}}"
        run: |
          echo "${{secrets.SSH_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \ 
            --list-only ${{env.dest}}
        # run: |
        #   echo "${{secrets.SSH_KEY}}" > deploy_key
        #   chmod 600 ./deploy_key
        #   rsync -chav --delete \
        #     -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
        #     --exclude /deploy_key \
        #     --exclude /.git/ \
        #     --exclude /.github/ \
        #     --exclude /theme-template/ \
        #     ./ ${{env.dest}}
